paths:
  MA_BANDS: &MA_BANDS "Datasets/MA_Bands.csv"
  METADATA: &METADATA "Datasets/metadata.csv"
  MA_SIMILAR: &MA_SIMILAR "Datasets/MA_Similar.csv"
  MA_DISCOG: &MA_DISCOG "Datasets/MA_Discog.csv"
  MA_DETAILS: &MA_DETAILS "Datasets/MA_Details.csv"
  MA_MEMBER: &MA_MEMBER "Datasets/MA_Member.csv"
  CONFIG: "Config.json"

keys:
  *MA_BANDS: ['band_id']
  *MA_SIMILAR: ['band_id', 'similar_id']
  *MA_DISCOG: ['name', 'type', 'year', 'band_id']
  *MA_DETAILS: ['band_id']
  *MA_MEMBER: ['band_id', 'member_id']
  *METADATA: ['name']

urls:
  MODIFIED: "https://www.metal-archives.com/archives/ajax-band-list/by/modified/selection/"
  BANDS: "https://www.metal-archives.com/browse/ajax-letter/json/1/l/"

python:
  PYTHONPATH: "."
  
scraper:
  RETRIES: 10
  DELAY: 0.3