scraper:
  RETRIES: 10
  DELAY: 0.3
  BATCH_SIZE: 1000

urls:
  MODIFIED: "https://www.metal-archives.com/archives/ajax-band-list/by/modified/selection/"
  BANDS: "https://www.metal-archives.com/browse/ajax-letter/json/1/l/"
  LABELS: "https://www.metal-archives.com/label/ajax-list/json/1/l/"
  REVIEWS: "https://www.metal-archives.com/reviews/1/1/"

paths:
  MA_BANDS: &MA_BANDS "Datasets/MA_Bands.csv"
  METADATA: &METADATA "Datasets/metadata.csv"
  MA_SIMILAR: &MA_SIMILAR "Datasets/MA_Similar.csv"
  MA_DISCOG: &MA_DISCOG "Datasets/MA_Discog.csv"
  MA_DETAILS: &MA_DETAILS "Datasets/MA_Details.csv"
  MA_MEMBER: &MA_MEMBER "Datasets/MA_Member.csv"
  MA_LABEL: &MA_LABEL "Datasets/MA_Label.csv"
  MA_REVIEWS: &MA_REVIEWS "Datasets/MA_Reviews.csv"

  GENRE: "Datasets/genre.csv"
  HGENRE: "Datasets/hgenres.csv"
  PREFIX: "Datasets/prefix.csv"
  GENRES: "Datasets/genres.csv"
  THEME: "Datasets/theme.csv"
  DIM_THEME_DICT: "Datasets/Temp/DIM_Theme_Dict.pkl"
  THEMES: "Datasets/themes.csv"
  CANDIDATES: "Datasets/candidates.csv"
  CONFIG: "Config.json"

keys:
  *MA_BANDS: ['band_id']
  *MA_SIMILAR: ['band_id', 'similar_id']
  *MA_DISCOG: ['album_id', 'band_id']
  *MA_DETAILS: ['band_id']
  *MA_MEMBER: ['band_id', 'member_id']
  *MA_LABEL: ['label_id']
  *MA_REVIEWS: ['album_id', 'review_id']
  *METADATA: ['name']

website:
# Backend for importing playlist data and embedding videos. Options: "YTDLP", "YTAPI" and "SCRAPE". 
  # YTAPI: requires own API key, free key has limited free recourses per day

  # YTDLP: No setup required and unlimited usage, same search results as YTAPI.

  # SCRAPE: Best search results as it includes playlists and embeds them as a video list that automatically plays all videos. 
    # Playlist importing uses YTDLP method.
    # Cons: Will break when/if youtube makes significant changes.

  YOUTUBE_BACKEND: "SCRAPE"

word_processing:
  UNWANTED_GENRE_WORDS: [
        "influences", 
        "earlier", 
        "later", 
        "early", 
        "or", 
        "mid", 
        "late", 
        "metal", 
        "from", 
        "elements", 
        "music"]
  BINARY_EXCEPTION: [
        "film score",
        "new age",
        "easy listening",
        "bossa nova",
        "new wave",
        "spoken word",
        "a cappella",
        "score",
        "age",
        "listening",
        "nova",
        "wave",
        "word",
        "cappella",
        "hop"]
  TERNARY_EXCEPTION: [
        "black 'n' roll",
        "rock 'n' roll",
        "death 'n' roll",
        "thrash 'n' roll",
        "drum and bass",
        "roll",
        "bass"]